version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - otters-network

networks:
  otters-network:
    external: true
    name: otters-network
